# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          # Fetch the latest commit, only
#          fetch-depth: 1
#      - name: Use Node.js 18.13
#        uses: actions/setup-node@v2
#        with:
#          node-version: 18.13
#          cache: 'npm'
#      - run: npm ci
#      - run: npm run lint

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          # Fetch the latest commit, only
#          fetch-depth: 1
#      - name: Use Node.js 18.13
#        uses: actions/setup-node@v2
#        with:
#          node-version: 18.13
#          cache: 'npm'
#      - run: npm ci
#      - run: npm run cover

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch the latest commit, only
          fetch-depth: 1
      - name: Use Node.js 18.13
        uses: actions/setup-node@v2
        with:
          node-version: 18.13
          cache: 'npm'
      - run: npm ci
      - run: npm run build

  update-release-draft:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          name: ${{ env.BUILD_VERSION }}
          tag: ${{ env.BUILD_VERSION }}
          version: ${{ env.BUILD_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
